services:
  web:
    build:
      context: .
    ports:
      - "7878:7878"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aether-network
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=aether
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - aether-network
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d aether"]
      interval: 3s
      timeout: 3s
      retries: 5
networks:
  aether-network:
    driver: bridge
volumes:
  db:
